#pragma once
#include <cstdint>
#include <algorithm>
#include <string>
#include <vector>
#include <cmath>
namespace arnis::map_renderer { struct Rgb{std::uint8_t r=0,g=0,b=0;}; inline Rgb shade(Rgb c,int y){double f=std::clamp(0.65+y*0.01,0.45,1.25);return{static_cast<std::uint8_t>(std::clamp(c.r*f,0.0,255.0)),static_cast<std::uint8_t>(std::clamp(c.g*f,0.0,255.0)),static_cast<std::uint8_t>(std::clamp(c.b*f,0.0,255.0))};} inline bool transparent(const char*n){return !n||std::string(n)=="air"||std::string(n)=="minecraft:air"||std::string(n)=="minecraft:cave_air";} inline Rgb blend(Rgb a,Rgb b,double t){t=std::clamp(t,0.0,1.0);return{static_cast<std::uint8_t>(a.r+(b.r-a.r)*t),static_cast<std::uint8_t>(a.g+(b.g-a.g)*t),static_cast<std::uint8_t>(a.b+(b.b-a.b)*t)};} }
namespace arnis::map_renderer { inline Rgb water_color(double depth){return blend({64,128,255},{8,32,96},std::clamp(depth/64.0,0.0,1.0));} inline Rgb snow_color(double depth){return blend({255,255,255},{180,200,220},std::clamp(depth/32.0,0.0,1.0));} }
namespace arnis::map_renderer { inline Rgb average(const std::vector<Rgb>&v){if(v.empty())return{};unsigned r=0,g=0,b=0;for(auto c:v){r+=c.r;g+=c.g;b+=c.b;}return{static_cast<std::uint8_t>(r/v.size()),static_cast<std::uint8_t>(g/v.size()),static_cast<std::uint8_t>(b/v.size())};} }
namespace arnis::map_renderer { inline std::vector<std::uint8_t> flatten_rgb(const std::vector<Rgb>&v){std::vector<std::uint8_t>o;o.reserve(v.size()*3);for(auto c:v){o.push_back(c.r);o.push_back(c.g);o.push_back(c.b);}return o;} }
namespace arnis::map_renderer { inline std::vector<Rgb> unflatten_rgb(const std::vector<std::uint8_t>&v){std::vector<Rgb>o;o.reserve(v.size()/3);for(std::size_t i=0;i+2<v.size();i+=3)o.push_back({v[i],v[i+1],v[i+2]});return o;} }
namespace arnis::map_renderer { inline std::vector<Rgb> shade_grid(const std::vector<Rgb>&v,int width,int height,const std::vector<int>&ys){std::vector<Rgb>o=v;for(std::size_t i=0;i<o.size()&&i<ys.size();++i)o[i]=shade(o[i],ys[i]);return o;} }
namespace arnis::map_renderer { inline std::vector<Rgb> blend_grids(const std::vector<Rgb>&a,const std::vector<Rgb>&b,double t){std::vector<Rgb>o;auto n=std::min(a.size(),b.size());o.reserve(n);for(std::size_t i=0;i<n;++i)o.push_back(blend(a[i],b[i],t));return o;} }
namespace arnis::map_renderer { inline Rgb contrast(Rgb c,double factor){return{static_cast<std::uint8_t>(std::clamp((c.r-128)*factor+128,0.0,255.0)),static_cast<std::uint8_t>(std::clamp((c.g-128)*factor+128,0.0,255.0)),static_cast<std::uint8_t>(std::clamp((c.b-128)*factor+128,0.0,255.0))};} inline std::vector<Rgb> contrast_grid(const std::vector<Rgb>&v,double f){std::vector<Rgb>o;o.reserve(v.size());for(auto c:v)o.push_back(contrast(c,f));return o;} }
namespace arnis::map_renderer { inline Rgb gamma_correct(Rgb c,double gamma){if(gamma<=0)gamma=1;auto f=[&](std::uint8_t v){return static_cast<std::uint8_t>(std::clamp(std::pow(v/255.0,gamma)*255.0,0.0,255.0));};return{f(c.r),f(c.g),f(c.b)};} inline std::vector<Rgb> gamma_grid(const std::vector<Rgb>&v,double g){std::vector<Rgb>o;o.reserve(v.size());for(auto c:v)o.push_back(gamma_correct(c,g));return o;} }
namespace arnis::map_renderer { inline Rgb grayscale(Rgb c){auto y=static_cast<std::uint8_t>(0.2126*c.r+0.7152*c.g+0.0722*c.b);return{y,y,y};} inline std::vector<Rgb> grayscale_grid(const std::vector<Rgb>&v){std::vector<Rgb>o;o.reserve(v.size());for(auto c:v)o.push_back(grayscale(c));return o;} }
namespace arnis::map_renderer { inline Rgb invert(Rgb c){return{static_cast<std::uint8_t>(255-c.r),static_cast<std::uint8_t>(255-c.g),static_cast<std::uint8_t>(255-c.b)};} inline std::vector<Rgb> invert_grid(const std::vector<Rgb>&v){std::vector<Rgb>o;o.reserve(v.size());for(auto c:v)o.push_back(invert(c));return o;} }
