#pragma once
#include <cstdint>
#include <tuple>
#include <utility>
#include <vector>
#include <algorithm>
#include <set>
#include "map_item_palette.h"
namespace arnis::map_item { constexpr int MAP_SIZE=128; constexpr int BUS_STOP_MAP_ID=2,RECYCLING_MAP_ID=3,HYDRANT_MAP_ID=4; std::tuple<int,std::int8_t,bool> map_geometry(int max_dimension); }
namespace arnis::map_item { inline std::pair<int,int> world_to_pixel(int x,int z,int min_x,int min_z,int blocks){return {(x-min_x)/blocks,(z-min_z)/blocks};} inline bool pixel_in_bounds(int x,int z){return x>=0&&x<MAP_SIZE&&z>=0&&z<MAP_SIZE;} }
namespace arnis::map_item { inline void accumulate_pixel(std::vector<std::uint32_t>&sum,std::vector<std::uint16_t>&count,int px,int pz,std::uint8_t r,std::uint8_t g,std::uint8_t b){if(!pixel_in_bounds(px,pz))return;auto i=static_cast<std::size_t>(pz*MAP_SIZE+px);if(sum.size()<MAP_SIZE*MAP_SIZE*3){sum.resize(MAP_SIZE*MAP_SIZE*3);count.resize(MAP_SIZE*MAP_SIZE);}sum[i*3]+=r;sum[i*3+1]+=g;sum[i*3+2]+=b;++count[i];} }
namespace arnis::map_item { inline std::vector<std::uint8_t> average_pixels(const std::vector<std::uint32_t>&sum,const std::vector<std::uint16_t>&count){std::vector<std::uint8_t> out(MAP_SIZE*MAP_SIZE*3);for(std::size_t i=0;i<count.size()&&i<MAP_SIZE*MAP_SIZE;++i)if(count[i]){out[i*3]=sum[i*3]/count[i];out[i*3+1]=sum[i*3+1]/count[i];out[i*3+2]=sum[i*3+2]/count[i];}return out;} }
namespace arnis::map_item { inline std::vector<std::uint8_t> quantize_pixels(const std::vector<std::uint8_t>&rgb,const std::vector<std::uint16_t>&count={}){std::vector<std::uint8_t> out(MAP_SIZE*MAP_SIZE);for(std::size_t i=0;i<out.size()&&i*3+2<rgb.size();++i)out[i]=(!count.empty()&&i<count.size()&&!count[i])?0:map_palette::nearest_map_color(rgb[i*3],rgb[i*3+1],rgb[i*3+2]);return out;} }
namespace arnis::map_item { inline std::vector<std::uint8_t> compose_map(const std::vector<std::uint32_t>&sum,const std::vector<std::uint16_t>&count){return quantize_pixels(average_pixels(sum,count),count);} }
namespace arnis::map_item { inline void overlay_map(std::vector<std::uint8_t>&base,const std::vector<std::uint8_t>&overlay,int ox,int oz){for(int z=0;z<MAP_SIZE;++z)for(int x=0;x<MAP_SIZE;++x){int dx=x+ox,dz=z+oz;if(pixel_in_bounds(dx,dz)&&z*MAP_SIZE+x<(int)overlay.size()&&overlay[z*MAP_SIZE+x])base[dz*MAP_SIZE+dx]=overlay[z*MAP_SIZE+x];}} }
namespace arnis::map_item { inline std::vector<std::uint8_t> transparent_map(){return std::vector<std::uint8_t>(MAP_SIZE*MAP_SIZE,0);} }
namespace arnis::map_item { inline std::vector<std::uint8_t> map_with_marker(std::vector<std::uint8_t> map,int x,int z,std::uint8_t color=4){if(pixel_in_bounds(x,z))map[z*MAP_SIZE+x]=color;return map;} }
namespace arnis::map_item { inline std::vector<std::uint8_t> rotate_map(const std::vector<std::uint8_t>&in,int quarter_turns){std::vector<std::uint8_t>o(MAP_SIZE*MAP_SIZE);int q=((quarter_turns%4)+4)%4;for(int z=0;z<MAP_SIZE;++z)for(int x=0;x<MAP_SIZE;++x){int nx=x,nz=z;if(q==1){nx=MAP_SIZE-1-z;nz=x;}else if(q==2){nx=MAP_SIZE-1-x;nz=MAP_SIZE-1-z;}else if(q==3){nx=z;nz=MAP_SIZE-1-x;}o[nz*MAP_SIZE+nx]=in[z*MAP_SIZE+x];}return o;} }
struct MapGeometry { int blocks_per_pixel=16; std::int8_t scale=0; bool marker=true; };
namespace arnis::map_item { inline MapGeometry geometry(int max_dimension){auto [b,s,m]=map_geometry(max_dimension);return {b,s,m};} inline std::vector<std::uint8_t> build_colors(const std::vector<std::uint8_t>&rgb,const std::vector<std::uint16_t>&samples={}){return quantize_pixels(rgb,samples);} }
namespace arnis::map_item { inline std::vector<std::uint8_t> render_rgb_grid(const std::vector<std::uint8_t>&rgb,int width,int height){if(width<=0||height<=0)return {};std::vector<std::uint8_t> out(MAP_SIZE*MAP_SIZE*3);for(int z=0;z<MAP_SIZE;++z)for(int x=0;x<MAP_SIZE;++x){int sx=std::min(width-1,x*width/MAP_SIZE),sz=std::min(height-1,z*height/MAP_SIZE);auto si=static_cast<std::size_t>((sz*width+sx)*3);auto di=static_cast<std::size_t>((z*MAP_SIZE+x)*3);if(si+2<rgb.size()){out[di]=rgb[si];out[di+1]=rgb[si+1];out[di+2]=rgb[si+2];}}return out;} }
namespace arnis::map_item { inline int next_map_id(const std::vector<int>&existing,int start=0){int id=std::max(0,start);for(;;++id)if(std::find(existing.begin(),existing.end(),id)==existing.end())return id;} inline std::vector<int> reserve_map_ids(int first,int count,const std::vector<int>&existing){std::vector<int> out;int id=first;for(int n=0;n<count;++n){id=next_map_id(existing,id);out.push_back(id);++id;}return out;} }
namespace arnis::map_item { inline std::vector<std::uint8_t> compose_preview(const std::vector<std::uint8_t>&rgb,int width,int height){return quantize_pixels(render_rgb_grid(rgb,width,height));} }
namespace arnis::map_item { inline std::vector<std::uint8_t> compose_preview_with_marker(const std::vector<std::uint8_t>&rgb,int width,int height,int marker_x,int marker_z){return map_with_marker(compose_preview(rgb,width,height),marker_x,marker_z);} }
namespace arnis::map_item { inline std::vector<std::uint8_t> compose_preview_rotated(const std::vector<std::uint8_t>&rgb,int width,int height,int quarter_turns){return rotate_map(compose_preview(rgb,width,height),quarter_turns);} }
struct MapArtifact { int id=0; std::int8_t scale=0; bool locked=true; std::vector<std::uint8_t> colors; };
namespace arnis::map_item { inline MapArtifact make_artifact(int id,const std::vector<std::uint8_t>&colors,std::int8_t scale=0){return{id,scale,true,colors};} inline std::vector<MapArtifact> make_artifacts(const std::vector<std::vector<std::uint8_t>>&maps,int first_id,std::int8_t scale=0){std::vector<MapArtifact>out;out.reserve(maps.size());for(std::size_t i=0;i<maps.size();++i)out.push_back(make_artifact(first_id+static_cast<int>(i),maps[i],scale));return out;} }
namespace arnis::map_item { inline void lock_artifacts(std::vector<MapArtifact>&a){for(auto&v:a)v.locked=true;} inline std::vector<int> artifact_ids(const std::vector<MapArtifact>&a){std::vector<int>out;out.reserve(a.size());for(const auto&v:a)out.push_back(v.id);return out;} }
namespace arnis::map_item { inline bool valid_artifact(const MapArtifact&a){return a.id>=0&&a.colors.size()==MAP_SIZE*MAP_SIZE;} inline std::vector<MapArtifact> valid_artifacts(const std::vector<MapArtifact>&a){std::vector<MapArtifact>out;for(const auto&v:a)if(valid_artifact(v))out.push_back(v);return out;} }
namespace arnis::map_item { inline std::vector<std::uint8_t> encode_artifact(const MapArtifact&a){std::vector<std::uint8_t> out;out.reserve(8+a.colors.size());out.push_back('A');out.push_back('M');for(int i=0;i<4;++i)out.push_back((a.id>>(i*8))&255);out.push_back(static_cast<std::uint8_t>(a.scale));out.push_back(a.locked?1:0);out.insert(out.end(),a.colors.begin(),a.colors.end());return out;} inline bool decode_artifact(const std::vector<std::uint8_t>&b,MapArtifact& a){if(b.size()<8||b[0]!='A'||b[1]!='M')return false;a.id=0;for(int i=0;i<4;++i)a.id|=int(b[2+i])<<(i*8);a.scale=static_cast<std::int8_t>(b[6]);a.locked=b[7]!=0;a.colors.assign(b.begin()+8,b.end());return valid_artifact(a);} }
namespace arnis::map_item { inline std::vector<std::uint8_t> encode_artifacts(const std::vector<MapArtifact>&a){std::vector<std::uint8_t>out;for(const auto&v:a){auto b=encode_artifact(v);std::uint32_t n=b.size();for(int i=0;i<4;++i)out.push_back((n>>(i*8))&255);out.insert(out.end(),b.begin(),b.end());}return out;} inline std::vector<MapArtifact> decode_artifacts(const std::vector<std::uint8_t>&b){std::vector<MapArtifact>out;std::size_t p=0;while(p+4<=b.size()){std::uint32_t n=0;for(int i=0;i<4;++i)n|=std::uint32_t(b[p++])<<(i*8);if(n> b.size()-p)break;MapArtifact a;if(decode_artifact(std::vector<std::uint8_t>(b.begin()+p,b.begin()+p+n),a))out.push_back(std::move(a));p+=n;}return out;} }
namespace arnis::map_item { inline void sort_and_deduplicate_artifacts(std::vector<MapArtifact>&a){std::sort(a.begin(),a.end(),[](const auto&x,const auto&y){return x.id<y.id;});a.erase(std::unique(a.begin(),a.end(),[](const auto&x,const auto&y){return x.id==y.id;}),a.end());} inline bool artifacts_roundtrip(const std::vector<MapArtifact>&a){auto encoded=encode_artifacts(a);auto decoded=decode_artifacts(encoded);return decoded.size()==a.size();} }
namespace arnis::map_item { inline int next_inventory_slot(const std::vector<int>&used,int first=0,int last=35){for(int s=std::max(0,first);s<=last;++s)if(std::find(used.begin(),used.end(),s)==used.end())return s;return -1;} inline std::vector<std::pair<int,int>> assign_inventory_slots(const std::vector<MapArtifact>&a,const std::vector<int>&used={}){std::vector<int> taken=used;std::vector<std::pair<int,int>> out;for(const auto&v:a){int slot=next_inventory_slot(taken);if(slot<0)break;out.emplace_back(slot,v.id);taken.push_back(slot);}return out;} }
namespace arnis::map_item { inline std::vector<int> map_ids_for_slots(const std::vector<std::pair<int,int>>&slots){std::vector<int>out;out.reserve(slots.size());for(const auto&p:slots)out.push_back(p.second);return out;} inline bool inventory_has_map(const std::vector<std::pair<int,int>>&slots,int id){return std::any_of(slots.begin(),slots.end(),[&](auto&p){return p.second==id;});} }
namespace arnis::map_item { inline std::vector<std::pair<int,int>> replace_inventory_map(const std::vector<std::pair<int,int>>&slots,int old_id,int new_id){auto out=slots;for(auto&p:out)if(p.second==old_id)p.second=new_id;return out;} inline std::vector<std::pair<int,int>> remove_inventory_map(const std::vector<std::pair<int,int>>&slots,int id){std::vector<std::pair<int,int>>out;for(auto&p:slots)if(p.second!=id)out.push_back(p);return out;} }
namespace arnis::map_item { inline std::vector<std::pair<int,int>> normalize_inventory(const std::vector<std::pair<int,int>>&slots){std::vector<std::pair<int,int>>out;std::set<int>used_slots,used_maps;for(auto&p:slots)if(p.first>=0&&p.first<36&&p.second>=0&&used_slots.insert(p.first).second&&used_maps.insert(p.second).second)out.push_back(p);std::sort(out.begin(),out.end());return out;} }
namespace arnis::map_item { inline std::vector<std::pair<int,int>> merge_inventory(const std::vector<std::pair<int,int>>&a,const std::vector<std::pair<int,int>>&b){auto out=a;out.insert(out.end(),b.begin(),b.end());return normalize_inventory(out);} inline std::vector<std::pair<int,int>> compact_inventory(const std::vector<std::pair<int,int>>&slots){auto n=normalize_inventory(slots);for(std::size_t i=0;i<n.size();++i)n[i].first=static_cast<int>(i);return n;} }
namespace arnis::map_item { inline std::vector<std::pair<int,int>> append_artifacts(const std::vector<std::pair<int,int>>&slots,const std::vector<MapArtifact>&artifacts){std::vector<std::pair<int,int>> add;for(const auto&a:artifacts)add.emplace_back(-1,a.id);auto out=slots;for(auto&p:add){int s=next_inventory_slot([&](){std::vector<int>v;for(auto&q:out)v.push_back(q.first);return v;}());if(s<0)break;out.emplace_back(s,p.second);}return normalize_inventory(out);} }
namespace arnis::map_item { inline std::vector<std::pair<int,int>> remove_invalid_artifacts(const std::vector<std::pair<int,int>>&slots,const std::vector<MapArtifact>&arts){std::set<int>valid;for(const auto&a:arts)if(valid_artifact(a))valid.insert(a.id);std::vector<std::pair<int,int>>out;for(auto&p:slots)if(valid.count(p.second))out.push_back(p);return normalize_inventory(out);} }
namespace arnis::map_item { inline std::vector<MapArtifact> artifacts_for_inventory(const std::vector<std::pair<int,int>>&slots,const std::vector<MapArtifact>&arts){std::set<int>ids;for(auto&p:slots)ids.insert(p.second);std::vector<MapArtifact>out;for(const auto&a:arts)if(ids.count(a.id))out.push_back(a);return out;} }
namespace arnis::map_item { inline bool inventory_artifacts_match(const std::vector<std::pair<int,int>>&slots,const std::vector<MapArtifact>&arts){auto have=artifacts_for_inventory(slots,arts);return have.size()==normalize_inventory(slots).size();} }
namespace arnis::map_item { class MapCatalog {
	std::vector<MapArtifact> artifacts_;
	std::vector<std::pair<int,int>> inventory_;
public:
	void add(MapArtifact artifact){ artifacts_.push_back(std::move(artifact)); sort_and_deduplicate_artifacts(artifacts_); }
	void add_all(const std::vector<MapArtifact>& artifacts){ artifacts_.insert(artifacts_.end(),artifacts.begin(),artifacts.end()); sort_and_deduplicate_artifacts(artifacts_); }
	void set_inventory(std::vector<std::pair<int,int>> slots){ inventory_=normalize_inventory(slots); }
	const std::vector<MapArtifact>& artifacts() const { return artifacts_; }
	const std::vector<std::pair<int,int>>& inventory() const { return inventory_; }
	std::vector<MapArtifact> valid_artifacts() const { return arnis::map_item::valid_artifacts(artifacts_); }
	void reconcile(){ artifacts_=valid_artifacts(); inventory_=remove_invalid_artifacts(inventory_,artifacts_); }
	std::vector<std::uint8_t> serialize() const { return encode_artifacts(artifacts_); }
	bool deserialize(const std::vector<std::uint8_t>& data){ auto decoded=decode_artifacts(data); if(data.size()&&!decoded.size()) return false; artifacts_=std::move(decoded); sort_and_deduplicate_artifacts(artifacts_); reconcile(); return true; }
	void assign_missing_slots(){ inventory_=append_artifacts(inventory_,artifacts_for_inventory(inventory_,artifacts_)); auto present=artifacts_for_inventory(inventory_,artifacts_); std::set<int> ids; for(const auto&a:present) ids.insert(a.id); std::vector<MapArtifact> missing; for(const auto&a:artifacts_) if(!ids.count(a.id)) missing.push_back(a); inventory_=append_artifacts(inventory_,missing); }
	std::vector<std::uint8_t> serialize_inventory() const { std::vector<std::uint8_t> out; for(const auto&p:inventory_){ out.push_back(static_cast<std::uint8_t>(p.first)); for(int i=0;i<4;++i) out.push_back((p.second>>(i*8))&255); } return out; }
	bool deserialize_inventory(const std::vector<std::uint8_t>& data){ if(data.size()%5) return false; std::vector<std::pair<int,int>> slots; for(std::size_t i=0;i<data.size();i+=5){ int id=0; for(int j=0;j<4;++j) id|=int(data[i+1+j])<<(j*8); slots.emplace_back(data[i],id); } inventory_=normalize_inventory(slots); return true; }
	std::vector<std::uint8_t> serialize_catalog() const { auto a=serialize(); auto i=serialize_inventory(); std::vector<std::uint8_t> out; std::uint32_t n=a.size(); for(int j=0;j<4;++j) out.push_back((n>>(j*8))&255); out.insert(out.end(),a.begin(),a.end()); out.insert(out.end(),i.begin(),i.end()); return out; }
	bool deserialize_catalog(const std::vector<std::uint8_t>& data){ if(data.size()<4) return false; std::uint32_t n=0; for(int j=0;j<4;++j)n|=std::uint32_t(data[j])<<(j*8); if(n>data.size()-4)return false; if(!deserialize(std::vector<std::uint8_t>(data.begin()+4,data.begin()+4+n)))return false; return deserialize_inventory(std::vector<std::uint8_t>(data.begin()+4+n,data.end())); }
	bool has_artifact(int id) const { return std::any_of(artifacts_.begin(),artifacts_.end(),[&](const auto&a){return a.id==id;}); }
	const MapArtifact* find_artifact(int id) const { for(const auto&a:artifacts_) if(a.id==id) return &a; return nullptr; }
	bool remove_artifact(int id){ auto old=artifacts_.size(); artifacts_.erase(std::remove_if(artifacts_.begin(),artifacts_.end(),[&](const auto&a){return a.id==id;}),artifacts_.end()); inventory_=remove_inventory_map(inventory_,id); return artifacts_.size()!=old; }
	std::size_t size() const { return artifacts_.size(); }
struct CatalogReport { std::size_t artifacts=0, valid=0, inventory_slots=0, orphan_slots=0; bool consistent=false; };
CatalogReport report() const { CatalogReport r; r.artifacts=artifacts_.size(); r.valid=valid_artifacts().size(); r.inventory_slots=inventory_.size(); for(const auto&p:inventory_) if(!has_artifact(p.second)) ++r.orphan_slots; r.consistent=(r.valid==r.artifacts&&r.orphan_slots==0); return r; }
bool repair(){ auto before=report(); reconcile(); assign_missing_slots(); auto after=report(); return before.consistent!=after.consistent || after.consistent; }
std::vector<int> missing_inventory_ids() const { std::set<int> present; for(const auto&p:inventory_) present.insert(p.second); std::vector<int> out; for(const auto&a:artifacts_) if(!present.count(a.id)) out.push_back(a.id); return out; }
std::vector<int> orphan_inventory_ids() const { std::vector<int> out; for(const auto&p:inventory_) if(!has_artifact(p.second)) out.push_back(p.second); return out; }
bool is_empty() const { return artifacts_.empty() && inventory_.empty(); }
void clear(){ artifacts_.clear(); inventory_.clear(); }
MapCatalog filtered_to_ids(const std::vector<int>& ids) const { std::set<int> keep(ids.begin(),ids.end()); MapCatalog out; for(const auto&a:artifacts_) if(keep.count(a.id)) out.add(a); for(const auto&p:inventory_) if(keep.count(p.second)) out.inventory_.push_back(p); out.inventory_=normalize_inventory(out.inventory_); return out; }
MapCatalog clone() const { MapCatalog out; out.artifacts_=artifacts_; out.inventory_=inventory_; return out; }
void merge_catalog(const MapCatalog& other){ for(const auto&a:other.artifacts_) add(a); inventory_=merge_inventory(inventory_,other.inventory_); reconcile(); }
bool equals(const MapCatalog& other) const { return artifacts_.size()==other.artifacts_.size()&&inventory_==other.inventory_&&std::equal(artifacts_.begin(),artifacts_.end(),other.artifacts_.begin(),[](const auto&a,const auto&b){return a.id==b.id&&a.scale==b.scale&&a.locked==b.locked&&a.colors==b.colors;}); }
std::vector<MapArtifact> unlocked_artifacts() const { std::vector<MapArtifact> out; for(const auto&a:artifacts_) if(!a.locked) out.push_back(a); return out; }
void set_locked(int id,bool locked){ for(auto&a:artifacts_) if(a.id==id) a.locked=locked; }
std::vector<std::uint8_t> export_color_atlas() const { std::vector<std::uint8_t> out; out.reserve(artifacts_.size()*MAP_SIZE*MAP_SIZE); for(const auto&a:artifacts_) out.insert(out.end(),a.colors.begin(),a.colors.end()); return out; }
std::vector<int> ordered_ids() const { auto out=artifact_ids(artifacts_); std::sort(out.begin(),out.end()); return out; }
bool replace(int id,MapArtifact replacement){ if(replacement.id!=id) return false; for(auto&a:artifacts_) if(a.id==id){a=std::move(replacement); return valid_artifact(a);} return false; }
std::vector<std::uint8_t> map_colors(int id) const { if(const auto*a=find_artifact(id)) return a->colors; return {}; }
bool set_colors(int id,std::vector<std::uint8_t> colors){ if(colors.size()!=MAP_SIZE*MAP_SIZE)return false; for(auto&a:artifacts_)if(a.id==id){a.colors=std::move(colors);return true;} return false; }
std::vector<int> locked_ids() const { std::vector<int> out; for(const auto&a:artifacts_) if(a.locked) out.push_back(a.id); return out; }
std::vector<int> ids_at_scale(std::int8_t scale) const { std::vector<int> out; for(const auto&a:artifacts_) if(a.scale==scale) out.push_back(a.id); return out; }
std::size_t total_color_bytes() const { std::size_t n=0; for(const auto&a:artifacts_) n+=a.colors.size(); return n; }
bool all_valid() const { for(const auto&a:artifacts_) if(!valid_artifact(a)) return false; return true; }
std::vector<int> duplicate_ids() const { std::vector<int> out; auto ids=artifact_ids(artifacts_); std::sort(ids.begin(),ids.end()); for(std::size_t i=1;i<ids.size();++i) if(ids[i]==ids[i-1]&&(out.empty()||out.back()!=ids[i])) out.push_back(ids[i]); return out; }
void deduplicate(){ sort_and_deduplicate_artifacts(artifacts_); inventory_=normalize_inventory(inventory_); reconcile(); }
}; }
namespace arnis::map_item { inline std::tuple<int,int,int,int> map_bounds(int min_x,int min_z,int max_x,int max_z){int d=std::max(max_x-min_x+1,max_z-min_z+1);auto [blocks,scale,marker]=map_geometry(d);(void)scale;(void)marker;return {min_x,min_z,min_x+MAP_SIZE*blocks-1,min_z+MAP_SIZE*blocks-1};} }
